# -*- coding: utf-8 -*-
# Generated by Django 1.10.7 on 2017-08-06 18:40
from __future__ import unicode_literals

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0003_auto_20170805_1012'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user',
            name='first_name',
            field=models.CharField(max_length=256, unique=True, validators=[django.core.validators.RegexValidator(code='invalid_first_name', message='Name must be Alphabetic', regex='^[a-zA-Z]*$')]),
        ),
    ]
